#!/usr/bin/env perl

require "perilconf";

$pkgname="utoolscross-zlib";
$pkgver="1.2.8";
$pkgrel="1";
$maintainer="linuxchrist@gmail.com";
$description="contains compression and decompression routines used by some programs.";
$homepage="https://zlib.net/";
@sources=("https://zlib.net/fossils/zlib-1.2.8.tar.gz", "https://zlib.net/fossils/zlib-0.8.tar.gz");
$arch="amd64";
$depends="";
$comment="uports: a universal linux/gnu ports collection";
&checkpkginfo; &checksources;
