#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection
. ./uports-config && PATH=$tpath

pkgname=crosstools-linux-headers
pkgver=6.6.3
pkgrel=1
maintainer="linuxchrist@gmail.com"
description="expose the kernel's API for use by Glibc."
homepage="https://www.kernel.org/"
sources="https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.6.3.tar.xz"
arch=amd64
depends=
comment="uports: a universal linux/gnu ports collection"
checkpkginfo

cd $usrc
if [ ! -f linux-6.6.3.tar.xz ]; then wget $sources; fi
tar -xvf linux-6.6.3.tar.xz
cd linux-$pkgver

mkdir $installdir/crosstools
ln -sv . $installdir/crosstools/usr
ln -sv lib $installdir/crosstools/lib64

make mrproper
make headers
make INSTALL_HDR_PATH=$installdir/crosstools/usr headers_install

defaultpackager
cd $usrc && rm -rf linux-$pkgver
cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
