#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection
. ./uports-config && PATH=$tpath

pkgname=crosstools-isl
pkgver=0.24
pkgrel=1
maintainer="linuxchrist@gmail.com"
description="a library for manipulating sets and relations of integer points bounded by linear constraints. "
homepage="https://libisl.sourceforge.io/"
sources="https://gcc.gnu.org/pub/gcc/infrastructure/isl-0.24.tar.bz2"
arch=amd64
depends=
comment="uports: a universal linux/gnu ports collection"
checkpkginfo

cd $src
if [ ! -f isl-0.24.tar.bz2 ]; then wget $sources; fi
tar -xvf isl-0.24.tar.bz2
cd isl-$pkgver

./configure --build=$build            \
	    --host=$build             \
	    --prefix=$cross           \
	    --enable-shared           \
	    --disable-static          \
	    --with-gmp=$cross         \
	    --with-gmp-prefix=$cross

make -j$(nproc)
make install DESTDIR=$installdir || exit $?

defaultpackager
cd $src && rm -rf isl-$pkgver
cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
