#!/usr/bin/env bash
#
#
# gcc 1st phaze disable libs
# gcc 2nd phaze not disable libs
# gcc 3rd phase enable libs
# uports: a universal linux/gnu ports collection
. ./uports-config && PATH=$tpath

pkgname=crosstools-gcc
pkgver=13.2.0
pkgrel=1
maintainer="linuxchrist@gmail.com"
description="contains the GNU compiler collection, which includes the C and C++ compilers."
homepage="https://gcc.gnu.org/"
sources="https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.xz"
arch=amd64
depends=
comment="uports: a universal linux/gnu ports collection"
checkpkginfo

cd $src
if [ ! -f gcc-13.2.0.tar.xz ]; then wget $sources; fi
tar -xvf gcc-13.2.0.tar.xz
cd gcc-$pkgver
mkdir ../gccbuild && cd ../gccbuild
../gcc-$pkgver/configure --build=$build			\
	    		 --host=$build			\
	    		 --target=$crosstarget		\
	    		 --prefix=$cross		\
	    		 --exec_prefix=$cross		\
	    		 --with-local-prefix=$cross	\
	    		 --with-sysroot=$cross		\
	 		 --disable-nls			\
			 --disable-shared               \
                         --disable-threads              \
			 --disable-multilib		\
			 --disable-libatomic		\
	    		 --disable-libgomp		\
	    		 --disable-libmudflap		\
	    		 --disable-libmpx		\
	    		 --disable-libssp		\
			 --disable-libvtv		\
	    		 --disable-libquadmath		\
	    		 --disable-libstdcxx		\
	    		 --with-gmp=$cross		\
	    		 --with-mpfr=$cross		\
	    		 --with-mpc=$cross		\
	    		 --with-isl=$cross		\
	    		 --with-glibc-version=2.38	\
			 --with-multilib-list=m64,m32,mx32 \
			 --enable-multilib		\
			 --enable-multiarch		\
			 --enable-languages=c,c++

make -j$(nproc)
make install DESTDIR=$installdir || exit $?

defaultpackager
cd $src && rm -rf gcc-$pkgver gccbuild
cd $pkgdir && dpkg --force-all -i $fullpkgname.deb
# end of file
