#!/usr/bin/env python

import pythonconfig

pkgname="crosstools-zlib"
pkgver="1.3"
pkgrel="1"
maintainer="linuxchrist@gmail.com"
description="contains compression and decompression routines used by some programs."
homepage="https://zlib.net/"
sources="https://zlib.net/fossils/zlib-1.3.tar.gz"
arch="amd64"
depends="none"
comment="uports: a universal linux/gnu ports collection"


#subprocess.run(['config.py'])
#subprocess.run(['002-zlib'])


