#!/usr/bin/env bash
#
#
# uports: a universal linux/gnu ports collection
. ./uports-config && PATH=$tpath

#ln -vs libgcc.a `$installdir/bin/${crosstarget}-gcc -print-libgcc-file-name | \
#    sed 's/libgcc/&_eh/'`

ln -sv libgcc.a	$installdir/utoolscross/lib/gcc/x86_64-cross-linux-gnu/13.2.0/libgcc_eh.a
